"""Builds Obsidian vault markdown pages from the Graphify knowledge graph."""

from __future__ import annotations

from pathlib import Path

from hw4.graphify.runner import GraphifyRunner
from hw4.shared.config import get_config


class ObsidianBuilder:
    """Generates index.md, hot.md, and supporting vault pages."""

    def __init__(
        self, runner: GraphifyRunner | None = None, vault_dir: str | Path | None = None
    ) -> None:
        cfg = get_config()
        self._runner = runner or GraphifyRunner()
        self._vault = Path(vault_dir or cfg.obsidian_dir)
        self._vault.mkdir(parents=True, exist_ok=True)

    def build_all(self) -> None:
        """Build all vault pages from graph data."""
        self._runner.load_graph()
        self._write_index()
        self._write_hot()

    def _write_index(self) -> None:
        top = self._runner.top_by_degree(20)
        lines = [
            "# scrapy - System Overview",
            "",
            "Auto-generated from `graph.json` by ObsidianBuilder.",
            "",
            "## Top Modules by Connectivity",
            "",
            "| Module | Degree |",
            "|--------|--------|",
        ]
        for name, degree in top:
            lines.append(f"| `{name}` | {degree} |")
        lines += [
            "",
            "## Architecture Blocks",
            "",
            "See [[architecture_blocks]]",
            "",
            "## OOP Summary",
            "",
            "See [[oop_summary]]",
            "",
            "## Bug Investigation",
            "",
            "See [[hot]] for top suspicious nodes.",
            "See [[fix_before_after]] for the applied patch.",
        ]
        (self._vault / "index.md").write_text("\n".join(lines), encoding="utf-8")

    def _write_hot(self) -> None:
        cfg = get_config()
        k = cfg.top_k_hot_nodes
        pr = self._runner.pagerank()
        top_pr = sorted(pr.items(), key=lambda x: x[1], reverse=True)[:k]
        lines = [
            "# Hot Nodes - Top Suspicious by PageRank",
            "",
            "Auto-generated by PageRank on `graph.json`. High-centrality nodes",
            "are most likely to be involved in bugs.",
            "",
            "| Rank | Node | PageRank Score |",
            "|------|------|---------------|",
        ]
        for rank, (node, score) in enumerate(top_pr, start=1):
            lines.append(f"| {rank} | `{node}` | {score:.6f} |")
        lines += [
            "",
            "## Focus: OffsiteMiddleware",
            "",
            "The `OffsiteMiddleware` node is the bug target. Its neighbors:",
            "- `CrawlerRunner`, `Engine`, `Spider`, `allowed_domains`",
            "",
            "Bug: `None` in `allowed_domains` causes `TypeError` in `should_follow`.",
        ]
        (self._vault / "hot.md").write_text("\n".join(lines), encoding="utf-8")

    def write_architecture_blocks(self) -> None:
        lines = [
            "# scrapy - Block Diagram",
            "",
            "```",
            "CLI (cmdline)",
            "    -> CrawlerRunner",
            "            -> Engine",
            "                    +-> Scheduler      (request queue)",
            "                    +-> Downloader     (HTTP fetch)",
            "                    |      -> Spider (parse + yield)",
            "                    -> Pipeline       (item processing)",
            "```",
            "",
            "Each block is a separate component connected via signals and middleware chains.",
        ]
        content = "\n".join(lines) + "\n"
        (self._vault / "architecture_blocks.md").write_text(content, encoding="utf-8")

    def write_oop_summary(self) -> None:
        content = """# scrapy - OOP Summary

| Class | Inherits | Role |
|-------|---------|------|
| `Spider` | `BaseSpider` | Define parse logic |
| `Request` | `object` | HTTP request wrapper |
| `Response` / `TextResponse` | `Response` | HTTP response |
| `Item` | `scrapy.Item` | Structured output |
| `MiddlewareMixin` | ABC | Download/spider middleware |
| `Extension` | ABC | Signal-based extensions |
| `Settings` | `ChainMap` | Layered configuration |
"""
        (self._vault / "oop_summary.md").write_text(content, encoding="utf-8")
